apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1nml
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1nml
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-1nml
  namespace: spadgett-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-1nml
status:
  loadBalancer: {}
